name: build

on:
  pull_request:
    branches: [master, main]
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: false

env:
  ENVIRONMENT: "staging"

jobs:
  build_pull_request:
    runs-on: ubuntu-20.04
    environment: staging

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.12.1

      # Skip post-install scripts here, as a malicious scripts can steal NODE_AUTH_TOKEN
      - name: Install Dependencies
        run: npm ci --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # `npm rebuild` will run all those post-install scripts for us
      - run: npm rebuild && npm run prepare --if-present

      - name: Bundle Application
        run: npm run build
